- name: Supervisord - Restart
  community.general.supervisorctl:
    name: '{{ ansible_user }}-all:'
    state: restarted
    supervisorctl_path: '/projects/{{ ansible_user }}/.local/bin/supervisorctl'
