export default [
  {
    id: 'http://www.wikidata.org/entity/Q1019527',
    type: 'Place',
    name: 'Reuver',
    slug: 'reuver',
    description: 'dorp in de Limburgse gemeente Beesel, Nederland',
    latitude: 51.285,
    longitude: 6.079167,
  },
  {
    id: 'http://www.wikidata.org/entity/Q124991822',
    type: 'Person',
    name: 'Cornelia Hennekam',
    slug: 'cornelia-hennekam',
    description: null,
    latitude: undefined,
    longitude: undefined,
  },
  {
    id: 'http://www.wikidata.org/entity/Q183',
    type: 'Place',
    name: 'Duitsland',
    slug: 'duitsland',
    description: 'land in West- en Centraal-Europa',
    latitude: 51,
    longitude: 10,
  },
  {
    id: 'http://www.wikidata.org/entity/Q223183',
    type: 'Person',
    name: 'Peter II van Joegoslavië',
    slug: 'peter-ii-van-joegoslavie',
    description: 'koning van Joegoslavië van 1934 tot 1945 (1923-1970)',
    latitude: undefined,
    longitude: undefined,
  },
  {
    id: 'http://www.wikidata.org/entity/Q34370',
    type: 'Place',
    name: 'Rotterdam',
    slug: 'rotterdam',
    description: 'havenstad in Zuid-Holland, Nederland',
    latitude: 51.92,
    longitude: 4.48,
  },
  {
    id: 'http://www.wikidata.org/entity/Q352',
    type: 'Person',
    name: 'Adolf Hitler',
    slug: 'adolf-hitler',
    description: 'dictator van nazi-Duitsland (1889–1945)',
    latitude: undefined,
    longitude: undefined,
  },
  {
    id: 'http://www.wikidata.org/entity/Q36600',
    type: 'Place',
    name: 'Den Haag',
    slug: 'den-haag',
    description: 'stad en gemeente in Zuid-Holland, Nederland',
    latitude: 52.08,
    longitude: 4.31,
  },
  {
    id: 'http://www.wikidata.org/entity/Q36704',
    type: 'Place',
    name: 'Joegoslavië',
    slug: 'joegoslavie',
    description:
      'tussen 1918 en 2003 de naam van meerdere opeenvolgende staten in Zuid-Europa op de Balkan. De hoofdstad was telkens Belgrado',
    latitude: 44.820556,
    longitude: 20.462222,
  },
  {
    id: 'http://www.wikidata.org/entity/Q64',
    type: 'Place',
    name: 'Berlijn',
    slug: 'berlijn',
    description: 'hoofdstad en deelstaat van Duitsland',
    latitude: 52.516667,
    longitude: 13.383333,
  },
  {
    id: 'http://www.wikidata.org/entity/Q690',
    type: 'Place',
    name: 'Delft',
    slug: 'delft',
    description: 'stad en gemeente in Zuid-Holland, Nederland',
    latitude: 52.011667,
    longitude: 4.359167,
  },
  {
    id: 'http://www.wikidata.org/entity/Q701',
    type: 'Place',
    name: 'Noord-Holland',
    slug: 'noord-holland',
    description: 'provincie van Nederland',
    latitude: 52.666667,
    longitude: 4.833333,
  },
  {
    id: 'http://www.wikidata.org/entity/Q727',
    type: 'Place',
    name: 'Amsterdam',
    slug: 'amsterdam',
    description: 'hoofdstad van Nederland, stad in Noord-Holland',
    latitude: 52.372778,
    longitude: 4.893611,
  },
  {
    id: 'http://www.wikidata.org/entity/Q966898',
    type: 'Organization',
    name: 'Algemeen Nederlands Persbureau',
    slug: 'algemeen-nederlands-persbureau',
    description: 'grootste Nederlandse persbureau',
    latitude: undefined,
    longitude: undefined,
  },
  {
    id: 'http://www.wikidata.org/entity/Q9920',
    type: 'Place',
    name: 'Haarlem',
    slug: 'haarlem',
    description: 'stad en gemeente in Noord-Holland, Nederland',
    latitude: 52.380278,
    longitude: 4.640556,
  },
  {
    id: 'https://adamlink.nl/geo/building/centraal-station/1208',
    type: 'Place',
    name: 'Centraal Station',
    slug: 'centraal-station',
    description: null,
    latitude: 52.378889,
    longitude: 4.900556,
  },
  {
    id: 'https://adamlink.nl/geo/building/koninklijk-concertgebouw/30',
    type: 'Place',
    name: 'Koninklijk Concertgebouw',
    slug: 'koninklijk-concertgebouw',
    description: null,
    latitude: 52.356244,
    longitude: 4.879046,
  },
  {
    id: 'https://adamlink.nl/geo/street/dam/880',
    type: 'Place',
    name: 'Dam',
    slug: 'dam',
    description: null,
    latitude: 52.37297,
    longitude: 4.893053,
  },
  {
    id: 'https://adamlink.nl/geo/street/damrak/882',
    type: 'Place',
    name: 'Damrak',
    slug: 'damrak',
    description: null,
    latitude: 52.375347,
    longitude: 4.896011,
  },
  {
    id: 'https://adamlink.nl/geo/street/gerrit-van-der-veenstraat/1497',
    type: 'Place',
    name: 'Gerrit van der Veenstraat',
    slug: 'gerrit-van-der-veenstraat',
    description: null,
    latitude: 52.348888,
    longitude: 4.874659,
  },
  {
    id: 'https://adamlink.nl/geo/street/roelof-hartplein/3856',
    type: 'Place',
    name: 'Roelof Hartplein',
    slug: 'roelof-hartplein',
    description: null,
    latitude: 52.353031,
    longitude: 4.882458,
  },
  {
    id: 'https://adamlink.nl/geo/street/rozenstraat/3901',
    type: 'Place',
    name: 'Rozenstraat',
    slug: 'rozenstraat',
    description: null,
    latitude: 52.37242,
    longitude: 4.879634,
  },
] as const;
