name: CI

on:
  push:
    branches:
      - develop
      - feature/ATM-170

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets: inherit
